host: localhost:8080
info:
  contact:
    name: API Support
    url: https://github.com/kics223w1/EndpointLab
  description: An alternative to httpbin.org in Gin.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: EndpointLab
  version: "1.0"
paths:
  /anything:
    delete:
      consumes:
      - application/json
      description: Return anything that is passed to the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Returns anything that is passed to request
      tags:
      - Anything
    get:
      consumes:
      - application/json
      description: Return anything that is passed to the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Returns anything that is passed to request
      tags:
      - Anything
    head:
      consumes:
      - application/json
      description: Return anything that is passed to the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Returns anything that is passed to request
      tags:
      - Anything
    options:
      consumes:
      - application/json
      description: Return anything that is passed to the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Returns anything that is passed to request
      tags:
      - Anything
    patch:
      consumes:
      - application/json
      description: Return anything that is passed to the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Returns anything that is passed to request
      tags:
      - Anything
    post:
      consumes:
      - application/json
      description: Return anything that is passed to the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Returns anything that is passed to request
      tags:
      - Anything
    put:
      consumes:
      - application/json
      description: Return anything that is passed to the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Returns anything that is passed to request
      tags:
      - Anything
  /cookies:
    get:
      consumes:
      - application/json
      description: Returns the cookies sent by the client
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Get cookies
      tags:
      - cookies
  /delete:
    delete:
      consumes:
      - application/json
      description: Returns the DELETE parameters of the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: The request's DELETE parameters.
      tags:
      - HTTP Methods
  /get:
    get:
      consumes:
      - application/json
      description: Returns the query parameters of the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: The request's query parameters.
      tags:
      - HTTP Methods
  /patch:
    patch:
      consumes:
      - application/json
      description: Returns the PATCH parameters of the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: The request's PATCH parameters.
      tags:
      - HTTP Methods
  /post:
    post:
      consumes:
      - application/json
      description: Returns the POST parameters of the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: The request's POST parameters.
      tags:
      - HTTP Methods
  /put:
    put:
      consumes:
      - application/json
      description: Returns the PUT parameters of the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: The request's PUT parameters.
      tags:
      - HTTP Methods
swagger: "2.0"
