definitions:
  api.httpAnythingResponse:
    properties:
      args:
        additionalProperties:
          type: string
        type: object
      data:
        type: string
      files:
        additionalProperties:
          type: string
        type: object
      form:
        additionalProperties:
          type: string
        type: object
      headers:
        additionalProperties:
          type: string
        type: object
      json: {}
      method:
        type: string
      origin:
        type: string
      url:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
    url: https://github.com/kics223w1/EndpointLab
  description: An alternative to httpbin.org in Gin.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: EndpointLab
  version: "1.0"
paths:
  /anything:
    delete:
      consumes:
      - application/json
      description: Return anything that is passed to the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.httpAnythingResponse'
      summary: Returns anything that is passed to request
      tags:
      - Anything
    get:
      consumes:
      - application/json
      description: Return anything that is passed to the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.httpAnythingResponse'
      summary: Returns anything that is passed to request
      tags:
      - Anything
    head:
      consumes:
      - application/json
      description: Return anything that is passed to the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.httpAnythingResponse'
      summary: Returns anything that is passed to request
      tags:
      - Anything
    options:
      consumes:
      - application/json
      description: Return anything that is passed to the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.httpAnythingResponse'
      summary: Returns anything that is passed to request
      tags:
      - Anything
    patch:
      consumes:
      - application/json
      description: Return anything that is passed to the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.httpAnythingResponse'
      summary: Returns anything that is passed to request
      tags:
      - Anything
    post:
      consumes:
      - application/json
      description: Return anything that is passed to the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.httpAnythingResponse'
      summary: Returns anything that is passed to request
      tags:
      - Anything
    put:
      consumes:
      - application/json
      description: Return anything that is passed to the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.httpAnythingResponse'
      summary: Returns anything that is passed to request
      tags:
      - Anything
  /cookies:
    get:
      consumes:
      - application/json
      description: Returns the cookies sent by the client
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Get cookies
      tags:
      - Cookies
  /cookies/delete:
    get:
      consumes:
      - application/json
      parameters:
      - description: Freeform cookie value
        in: query
        name: freeform
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Redirects to cookie list
          schema:
            type: string
      summary: Deletes cookie(s) as provided by the query string and redirects to
        cookie list.
      tags:
      - Cookies
  /cookies/set:
    get:
      consumes:
      - application/json
      parameters:
      - description: Freeform cookie value
        in: query
        name: freeform
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Redirects to cookie list
          schema:
            type: string
      summary: Sets cookie(s) as provided by the query string and redirects to cookie
        list.
      tags:
      - Cookies
  /cookies/set/{name}/{value}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Cookie name
        in: path
        name: name
        required: true
        type: string
      - description: Cookie value
        in: path
        name: value
        required: true
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Redirects to cookie list
          schema:
            type: string
      summary: Set a cookie with specified name and value
      tags:
      - Cookies
  /delete:
    delete:
      consumes:
      - application/json
      description: Returns the DELETE parameters of the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: The request's DELETE parameters.
      tags:
      - HTTP Methods
  /get:
    get:
      consumes:
      - application/json
      description: Returns the query parameters of the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: The request's query parameters.
      tags:
      - HTTP Methods
  /image:
    get:
      description: Returns a simple image of the type suggested by the Accept header
      produces:
      - image/webp
      - ' image/png'
      - ' image/jpeg'
      - ' image/svg+xml'
      responses:
        "200":
          description: OK
          schema:
            type: file
        "406":
          description: Not Acceptable
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Returns an image based on the Accept header
      tags:
      - Images
  /image/jpeg:
    get:
      description: Returns a simple JPEG image
      produces:
      - image/jpeg
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: Returns a JPEG image
      tags:
      - Images
  /image/png:
    get:
      description: Returns a simple PNG image
      produces:
      - image/png
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: Returns a PNG image
      tags:
      - Images
  /image/svg:
    get:
      description: Returns a simple SVG image
      produces:
      - image/svg+xml
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: Returns an SVG image
      tags:
      - Images
  /image/webp:
    get:
      description: Returns a simple WEBP image
      produces:
      - image/webp
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: Returns a WEBP image
      tags:
      - Images
  /patch:
    patch:
      consumes:
      - application/json
      description: Returns the PATCH parameters of the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: The request's PATCH parameters.
      tags:
      - HTTP Methods
  /post:
    post:
      consumes:
      - application/json
      description: Returns the POST parameters of the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: The request's POST parameters.
      tags:
      - HTTP Methods
  /put:
    put:
      consumes:
      - application/json
      description: Returns the PUT parameters of the request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: The request's PUT parameters.
      tags:
      - HTTP Methods
  /status/{code}:
    delete:
      description: Returns a status code based on the path
      parameters:
      - description: HTTP Status Code
        in: path
        name: code
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Return status code or random status code if more than one are given
      tags:
      - Status
    get:
      description: Returns a status code based on the path
      parameters:
      - description: HTTP Status Code
        in: path
        name: code
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Return status code or random status code if more than one are given
      tags:
      - Status
    head:
      description: Returns a status code based on the path
      parameters:
      - description: HTTP Status Code
        in: path
        name: code
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Return status code or random status code if more than one are given
      tags:
      - Status
    options:
      description: Returns a status code based on the path
      parameters:
      - description: HTTP Status Code
        in: path
        name: code
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Return status code or random status code if more than one are given
      tags:
      - Status
    patch:
      description: Returns a status code based on the path
      parameters:
      - description: HTTP Status Code
        in: path
        name: code
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Return status code or random status code if more than one are given
      tags:
      - Status
    post:
      description: Returns a status code based on the path
      parameters:
      - description: HTTP Status Code
        in: path
        name: code
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Return status code or random status code if more than one are given
      tags:
      - Status
    put:
      description: Returns a status code based on the path
      parameters:
      - description: HTTP Status Code
        in: path
        name: code
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Return status code or random status code if more than one are given
      tags:
      - Status
swagger: "2.0"
